[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "067b7a7af1fbc1a44694842eb8aa2d264d14f3e3"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "3ebbea7ef55e99621848e96647d6bdec70b34c877764231304a445ec732bdb01"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.aarch64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "0dbd3336553e4a6ef1d88db5c949150f5dfa6947"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "54e9aea8d30dc58e144da188e20545659a48d148c91449aa22245543f6703c7b"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.aarch64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "4133c2450cc7e54118606ef6a7b3c287befcb4f6"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "2ba57b08be5fd6eac724dd9dad6a020b97f55b668f962527a56831ba883fd243"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.aarch64-unknown-freebsd.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d2462d4f0e2c08328ffa393f0232d26deea175a"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "a2ffa090828736b6c03ae4f78951d2a5e637d502740f40a4aeb40a04199e0129"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.armv6l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8315447455c3d4aee152330cfb5ef39ca1d6eb41"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "fe2e7cbf3312e68b6f85ab6f657d03d1c6aaf579d294d55558d29ab83e73046a"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.armv6l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c16d822a3cbb225924874289afdfa72665041e8"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "3f32966355a2963437f8cfedf40d917c21133b34bd55877a0b138c2ef6b34dde"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.armv7l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9a4410d5440626c9d74e33c1dba6674af75976f"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "e0af3e98ba01b13efa5c1946cad1df93aeeaacaa52462017a416cef15b40e72a"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.armv7l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "a04f3aca3f2e5becf4b99c468ecbbf8ec34f9975"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "1e24f94893169fc1c145da54b249e1b246c3e1f959b0bfb37086a39cea0aeb72"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.i686-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "cf8b245279893775b0b9dd6977d224d5d7ba2057"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "4776d691470a380bf52ea2ea622fa7449a40c59f39d52c01a34b5ee244dc5a12"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.i686-linux-musl.tar.gz"
[[s2n_tls]]
arch = "powerpc64le"
git-tree-sha1 = "e103e3dc15c6e108ba891f2167344dedbe4caaa6"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "c38dac784cbd349b89b3b34a351732c80beb6b583760c66d692c5bc5aecfd75c"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.powerpc64le-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "riscv64"
git-tree-sha1 = "fe725055eebca46bb339ab88acb42282a1c0e099"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "7927eb0dcacaafc548e2a2569959d30372c67fc4f7a4b344a239512fd022c08a"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.riscv64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "22c571e13c3bba5475368213d33cb10732be61c8"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "dc25ef046877629a6e6c79301d055bdedb81377d44e5f9b79b8af9b8c4291919"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.x86_64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "deb494a67636f5325937fa528f6b67214555ee5c"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "5812c07c09c0e93273f01af88c5c1acab7b647fcf3ebc3fd8f88365defa66156"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.x86_64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "3d9b24ff8ef0ce01247f8d52d9f32c7c4ab5262a"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "1b3f71347ac54943764bb281f1d8ace6a21b4f8d447831bdb31758c8570f693c"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.2+0/s2n_tls.v1.6.2.x86_64-unknown-freebsd.tar.gz"
