[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "5f1b53f7655e45a924625667792a75a46fbb738e"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "30a15574b8464b2a79e6ca8bfa0ba6cf3f00cd59b43d60e99e6c6529eeba5c81"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.aarch64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "b512a993850422cecc2026e89bb5478a8bd6bc3d"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "07658599e67b8ee661a4ad60ab8fb7cf257771c1471806d41a3e88ed77dd0815"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.aarch64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "00e81bfa43c65752bcaa7fb80c3527b17d40a718"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "ce33003b9b359107034b06b80ed79f79737abe77aecd0fb865d03e9070df85ca"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.aarch64-unknown-freebsd.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12ccc8490aafe9d296be3291f9f59d0f744762fe"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "95ee2322cdcee9613cc54bb6d240deedbff86f38ed027deab9cf97ca8619ee53"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.armv6l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39446d6697cb7a89a0babcb92609be361f9363a2"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "abbcb032b35887dc3118b60b4de856c2f70b860a2de2ff4562cfc7185796f8e5"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.armv6l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bf6ebd3ecb602b815d9fb44380c2688614f28a3a"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "2d4929e38fb3fa515be2f9a48a73a42a3c4def45687794eebe9833696e7bc1d9"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.armv7l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abac61ffff637bfc968e4f5dc474ec3d13e28bf4"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "43756aad009bc05303e17a162f42e94e5771e5d12aded0a3cdd8065ffdacc2d0"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.armv7l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "67a7f327551c9ec4eb13757625355d90f17681f0"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "349e5f0142f4d1768b2f5a4242cfb584d33a5f08403d4f92ebf096357ed8395c"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.i686-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "905a7c826e4ebf1c3e3406ba85e3676460d01de9"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "a8ca521bc128292a9c684ba72728040e43be638d8591b4fea969c28419c0fffe"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.i686-linux-musl.tar.gz"
[[s2n_tls]]
arch = "powerpc64le"
git-tree-sha1 = "4b6d08e1cbc310ed5e3db0a402d538ca3d96ff56"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "0daac5171b0c5ebe22b4ac4723b22deb8cd2211946356606f5347eb9df65d4b5"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.powerpc64le-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "riscv64"
git-tree-sha1 = "a7575eb9e36bb62cc0ed311597c294468eea5ac3"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "33aa485e7c035818b6dfd2816da7b9ebcab06c311bc15cd54919c79840567b03"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.riscv64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "72441568d66819e9d9a80c5b2771dc78062700e5"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "2a4de20e5b6c0a33bdf13ff60ce9b91957f1172afd4958ee4da8ca417eedf62a"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.x86_64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "523b4026048ebd639def443b75274dcbbfe707d8"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "482dfd2ef54e556490d2c5e746af396d348b6289a23145452e8407ee2b9ad9eb"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.x86_64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "4f4d7278c19c53157c2f5975a8acf31f2606f8db"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "ed82f5ba7a8b54fd9888a921c8e9d5e7717c38e011ca6ec61d1051dd16a8c007"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.4+0/s2n_tls.v1.6.4.x86_64-unknown-freebsd.tar.gz"
