[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "a9a83cd64c9ad1824896fe2c966bfb230f13a60b"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "dd33ba3e36c8db0f2bc2a3e555065090040f6b6e508f2764429b195d1142394b"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.aarch64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "70eff26615bc20d796ba3fbed7b8f3e9c631196f"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "411a9dc98cd751c0ce3bad29d3e1a61951e8767411c2ed30f022d97b7e157569"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.aarch64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "510557aa6ff3cb19e63666b2dee4cba0372e5ca3"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "87217c47226afe68c2535218f7ddb9bedf4a13aab93d5163beb2d3506c2bd554"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.aarch64-unknown-freebsd.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "86b47d02b124c2df02aabfce6ef00aec006be8a0"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "51aaea3a7bfd3a71193253425e7776941b030376594a312959f00df358ed859f"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.armv6l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c995b8a112872e4b8938a272980dd0e51b6a11df"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "a659f7a165d9af408525d35027d07a318d13a4668a9559b2c2057dc070277294"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.armv6l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2e413a231fd455a0e7684d1a36a1aeb69989dd4"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "00f04f18b936124f75fd7600be29193908f519eab15bbe7d4002719a5ed60fe9"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.armv7l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d55bdece7b7f631e664e278eb886c40b2d8c813"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "42965ccd8c814e64b05618679fa21834c867700f4cdd07516e78ec2e30915065"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.armv7l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "6c2b5b47447cddea4e3907fd2f330a5ab6d66296"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "3b09401b0abcd9c249fe189c17320673e174657c983dad6752b16d52e27ca369"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.i686-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "0b46540811574a476777afa74086a65d049ae3bc"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "11b1fbf7c1d30938e36740ddd72ddafad491ab1d58aba4f215776ddbdbf8653f"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.i686-linux-musl.tar.gz"
[[s2n_tls]]
arch = "powerpc64le"
git-tree-sha1 = "43dd337b023efb0008821b1e00ba097f8a4b74da"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "5f7459cd389962c4f348e894453128031152cdbbb65fae13da6a46c6be5a657f"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.powerpc64le-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "riscv64"
git-tree-sha1 = "7ae0bf8d76753dcca94353eb4bb7744c48fb2131"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "66e43e04c97d16ecd5464d9028cf2c14e63649c0b68caaa26e8a1469228e3f7e"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.riscv64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "2a080868034c7c938f2bcfdf1048347d9638e422"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "3122ab17f1b67d70133fa596a8395b3ecb264877c515376622345f886c1e80c5"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.x86_64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "70abe8d0109cf8576eeab971d8265d26549e4e3d"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "d910d50b73008ece6f98d2cc3de33a257cd3b3b76468a89947001d4df8f6389b"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.x86_64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "417d9b3028f61a64fb1beaea89b1a7a6f231f94c"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "3c251775341c41e666110045a5226e77754a21ec1d1e0290388f553e0bba584c"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.0+0/s2n_tls.v1.6.0.x86_64-unknown-freebsd.tar.gz"
