[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "57c1489d1be0d2fa34f05fa0e8ac6b7aae203cbb"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "0e58e6ea519789d013069f75e334ab24bb85492136ae06574db7a155af7e2ef8"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.aarch64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "1fc43352abbf0750ee6fda93a021004bf4f3c763"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "a33084bfe225d7ce17bff4a123a220e92e82cf8b46e18c66abfae84acb033774"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.aarch64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "e60785dd41b63382ce0658d18936d19a378c5487"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "0c7cf1ba0730bccac663b19106206850a34f70b3fbf6bf5735dd01d274477147"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.aarch64-unknown-freebsd.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc8b1ebd8144cacd6931b099d30f8dbf15d9c6db"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "aa700d9e387d3e087d3316f7d44f63c078bf0c3e608c0ae91fda7df9a1fdd5bd"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.armv6l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b9d6372b172ec93eeaba96537f7202a48d1eb978"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "b8aa7afe119fe842471dc1bf17dcadeac20ce50d71c44c4f79eda635abe9ccba"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.armv6l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "deaff74d0eb8f82cd4ab22ca5173503d02a537b6"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "496a38b40def784c9182174b5f1358c818b7055e4687bcbfdd1a9e16f11fc7a1"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.armv7l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef7e16783bc98d401e86a956784f7048666cb325"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "abc0c4a9c21d65ffbceafd039eb5c42357ad5f3b4781c873c42859308ef05d2a"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.armv7l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "8b16d5989e6fa6c2814038ffee01228136c51f9a"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "86ecc8316987ffbd1af14d3a133cd7305469e0639aa241d4173a1743a6e2db70"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.i686-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "b3139e204da0f02b4cd3b214ae807d2dd6a260ba"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "b553897ed56cb58e12275ee03c67906bc342f87ef57579daa1bcc369e9020127"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.i686-linux-musl.tar.gz"
[[s2n_tls]]
arch = "powerpc64le"
git-tree-sha1 = "b70e1fa82b31993055ff6dd9b048bbb20744139b"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "eec49e736d061d54b181ff6c6d5ba8575de117c3e16c47c6f3ee5bc8cafb5c7c"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.powerpc64le-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "riscv64"
git-tree-sha1 = "eafdcdfa73b6f338398fe47e998639eb46dbe1a6"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "1b2f5a95e5064639357d47d482a6791e22ca5e582ede023da7ce09fe9cf7d898"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.riscv64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "17d2ff77e95b6ecbd2d22af1d6e26dda310bf899"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "f96d86d9a2ac4e009ac0b1d4d2babda4675e134e91ed3b50324f8ec0b0e4f950"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.x86_64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "e42e58f2ecaac01e4cbff67dfbda04dfe349bdd9"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "04d8c49bec57d19ddb1cf8245053fe9404ec40e0d1c7ba74032e34c045438235"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.x86_64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "e92ed9205fc3dabe6ccb8e1add53a97dedc5e8bd"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "0f42a4b208672b05dfe4724646bc674083fda66bb84d436dbf14da19a14cd493"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.6.3+0/s2n_tls.v1.6.3.x86_64-unknown-freebsd.tar.gz"
